import Link from "next/link";
import Image from "next/image";

export default async function Voorwaaarden() {
    return (
       <div className="container">
           <h1 className="text-6xl w-full md:w-5/12">Algemene voorwaarden DB WEBDEVELOPMENTS COMM.V.</h1>
           <p>(B2B EN B2C)
               ARTIKEL 1 – TOEPASSELIJKHEID - OVEREEN– KOMST
               1.1.	DB WEBDEVELOPMENTS COMM.V. (hierna: “BYTEKLAAR”), met zetel te 3665 As, Lanklaarsesteenweg 31, en met ondernemingsnummer 1000.698.817 (info@byteklaar.be of 0477 20 99 33) is een onderneming gespecialiseerd in computerconsultancy-activiteiten, prepress- en premediadiensten, ontwerpen en beheren van websites en webshops, gegevensverwerking en andere aanverwante activiteiten.
               1.2.	Onderhavige algemene voorwaarden zijn van toepassing op alle offertes, opdrachten, orderbevestigingen, bestelbonnen en overeenkomsten gesloten tussen BYTEKLAAR en de klant, alsook de uitvoering ervan. Zij maken integraal deel uit van de overeenkomst tussen BYTEKLAAR en de klant. Onderhavige algemene voorwaarden zijn van toepassing met uitsluiting van de eventuele algemene voorwaarden van de klant.
               1.3.	De klant zal kennis kunnen nemen van onderhavige algemene voorwaarden voor het sluiten van de overeenkomst. Na kennisname en aanvaarding ervan, zullen deze algemene voorwaarden op de klant van toepassing zijn.
               1.4.	BYTEKLAAR behoudt zich het recht voor de algemene voorwaarden te allen tijde te wijzigen. Eventuele wijzigingen zullen van toepassing worden op elke nieuwe overeenkomst. Voor lopende overeenkomsten op het ogenblik van de wijziging, blijven de algemene voorwaarden gelden zoals bestaande tijdens de totstandkoming, tenzij de gewijzigde algemene voorwaarden tijdens de duur van de overeenkomst door de klant worden aanvaard.
               1.5.	Alle bijlagen die zijn toegevoegd aan de offerte, orderbevestiging, overeenkomst of factuur maken integraal deel uit van de contractuele relatie tussen partijen en kunnen een aanvulling, dan wel een wijziging op de algemene voorwaarden inhouden.
               1.6.	Indien zich een situatie zich voordoet dewelke niet geregeld werd in onderhavige algemene voorwaarden, dient deze geïnterpreteerd te worden conform het gemene recht rekening houdende met de geest van deze algemene voorwaarden.
               1.7.	De rechtstreekse leveringen uitgaande van onderaannemers, toeleveranciers etc. gebeuren volgens de voorwaarden van deze laatsten, behoudens uitdrukkelijk anders bepaald in de offerte of orderbevestiging en verstaande zijnde dat de aansprakelijkheid van BYTEKLAAR alleszins begrensd is door onderhavige algemene voorwaarden.
               1.8.	Het aanbod van diensten, goederen en producten geldt zo lang de voorraad strekt. In geval van (tijdelijke) uitputting van de voorraad behoudt BYTEKLAAR zich het recht voor om de opdracht niet te accepteren, dan wel om in soortgelijke diensten, goederen en producten te voorzien mits goedkeuring van de klant.
               1.9.	Verbintenissen aangegaan door aangestelden van BYTEKLAAR zijn slechts geldig na bevestiging ervan door een bestuurder of bevoegde gevolmachtigde van BYTEKLAAR. De aanvaarding van een opdracht door BYTEKLAAR gebeurt onder voorbehoud van haar (toe)leveranciers waarop zij beroep dient te doen ter uitvoering van de bestelling. Indien een (toe)leverancier de bestelling weigert, verbinden partijen zich tot het onderhandelen van een alternatief dat voor beide partijen als afdoende wordt geacht. In geval er door de fout van de klant een verkeerde bestelling werd geplaatst bij de (toe)leverancier, zal BYTEKLAAR hier niet voor aansprakelijk kunnen worden gesteld.
               ARTIKEL 2 – OFFERTES, BESTELLINGEN EN MEERWERKEN
               2.1.	Alle offertes en aanbiedingen van BYTEKLAAR
               zijn vrijblijvend en worden steeds gemaakt onder alle voorbehoud. Tenzij anders is vermeld in de offerte, is deze geldig gedurende een periode van 30 kalenderdagen (B2B en B2C). Indien de klant pas na het verstrijken van de geldigheidsduur ingaat op de offerte, is BYTEKLAAR niet gebonden aan de in de offerte weergegeven prijzen en modaliteiten. In dat geval zal BYTEKLAAR de op dat moment geldende prijzen en modaliteiten aan de klant communiceren in een nieuwe offerte. De klant heeft in dat geval de keuze om erop in te gaan of niet.
               2.2.	Bestellingen of aanvragen dienen uitsluitend
               schriftelijk te worden geplaatst. Een offerte of aanvraag wordt pas bindend door BYTEKLAAR nadat deze integraal en schriftelijk is bevestigd door BYTEKLAAR en het voorschot van minstens 35% van de totale offerteprijs is betaald.
               2.3.	BYTEKLAAR ziet toe op een nauwkeurige product-
               en dienstenomschrijving. In geval van ernstige afwijking tussen de goederen of diensten en de beschrijving en/of weergave ervan, meldt BYTEKLAAR dit onverwijld aan de klant en behoudt BYTEKLAAR zich het recht voor af te zien van uitvoering van de overeenkomst mits restitutie van het reeds betaalde. BYTEKLAAR is slechts gehouden tot een middelenverbintenis voor wat de juistheid en/of volledigheid van de aangeboden informatie in offertes, overeenkomsten, orderbevestigingen, bestelbonnen of op de website betreft en draagt geen aansprakelijkheid voor materiële vergissingen zoals typfouten.
               2.4.	Wijzigingen aan de offerte, bestelbon of overeen-
               komst, en aldus aan de opdracht, dienen onverwijld schriftelijk (per aangetekende brief of e-mail) kenbaar gemaakt te worden door de klant en zijn enkel mogelijk na schriftelijke aanvaarding van BYTEKLAAR. Wijzigingen die worden doorgegeven op het ogenblik dat de opdracht zich reeds in uitvoering bevindt, kunnen niet worden behandeld, tenzij mits goedkeuring van BYTEKLAAR. Wijzigingen die door de klant worden doorgegeven op het ogenblik dat de opdracht zich reeds in uitvoering bevindt, kunnen niet worden behandeld, tenzij mits goedkeuring van BYTEKLAAR. In geval van tijdig en aanvaard verzoek, behoudt BYTEKLAAR zich het recht voor tot het dienovereenkomstig aanpassen van de offerte of prijsopgave. Als een verzoek mondeling gebeurt, is het risico voor het al dan niet uitvoeren van de wijzigingen voor rekening van de klant.
               2.5.	Aan de offerte of overeenkomst supplementaire
               opdrachten of diensten zullen het recht doen ontstaan op additionele vergoeding in hoofde van BYTEKLAAR. Deze meerwerken worden aangerekend conform de bepalingen onder artikel 7.2., behoudens in geval van afwijkende schriftelijke afspraken tussen partijen.
               2.6.	BYTEKLAAR behoudt zich het recht voor om een
               opdracht te weigeren wanneer deze indruist tegen de toepasselijke wettelijke bepalingen, reglementen of overheidsbevelen, evenals opdrachten waarvan de inhoud strijdig is met de goede naam of waarden waarvoor BYTEKLAAR staat.
               ARTIKEL 3 – VERTEGENWOORDIGING
               3.1.	    Door het ondertekenen van de offerte, orderbevestig-
               ing, bestelbon of andere overeenkomst verbindt de klant zich definitief.
               3.2.	    Iedere persoon of maatschappij die opdrachten
               plaatst voor rekening van derden of met het verzoek ze aan derden te factureren maakt zich sterk voor deze derden en zal persoonlijk aansprakelijk zijn voor de betaling, zelfs indien BYTEKLAAR akkoord ging met een andere wijze van facturering.
               ARTIKEL 4 – ALGEMENE VERPLICHTINGEN VAN BYTEKLAAR
               4.1.	    In principe worden de werkzaamheden uitsluitend
               uitgevoerd op werkdagen. In geval van uitzonderlijke en bijzondere omstandigheden die werkzaamheden van BYTEKLAAR in het weekend en/of op feestdagen vereisen, kan hier in onderling overleg evenwel van worden afgeweken. In dat geval behoudt BYTEKLAAR zich het recht voor tot het aanrekenen van meerwerken conform artikel 7.2.
               4.2.	    BYTEKLAAR zal de door haar te verrichten opdracht
               naar beste inzicht en vermogen uitvoeren overeenkomstig de eisen van goed vakmanschap en dit binnen een redelijke termijn. Partijen komen uitdrukkelijk overeen dat de verplichtingen van BYTEKLAAR het karakter hebben van een inspanningsverbintenis, tenzij afwijkend vastgesteld. Geringe wijzigingen door BYTEKLAAR in de opdracht die geen afbreuk doen aan de kwaliteit van de werkzaamheden zijn toegestaan.
               4.3.	    Tenzij anders overeengekomen tussen partijen,
               behoudt BYTEKLAAR de volledige vrijheid in het aanwenden van de lay-out.
               4.4.	    BYTEKLAAR is gerechtigd haar rechten of
               verplichtingen voortvloeiend uit de overeenkomst over te dragen aan derden in onderaanneming, teneinde aan de vereisten van goed vakmanschap te voldoen.
               4.5.	    BYTEKLAAR verbindt zich tot het vertrouwelijk
               behandelen van alle informatie die haar wordt verstrekt door de klant en zal deze enkel aanwenden ten behoeve van de klant in het kader van de toevertrouwde opdracht.
               ARTIKEL 5 – ALGEMENE VERPLICHTINGEN VAN DE KLANT
               5.1.	    De klant verbindt zich ertoe alle informatie tijdig te
               verstrekken die noodzakelijk geacht wordt om de opdracht op doeltreffende wijze te kunnen uitvoeren. Dit omvat, maar is niet beperkt tot, het verstrekken van de nodige feedback binnen de 10 kalenderdagen na elke vergadering met BYTEKLAAR. De klant erkent dat het geven van deze feedback essentieel is voor een vlot verloop van het project. De klant staat verder in voor de juistheid, volledigheid en betrouwbaarheid van alle verstrekte gegevens en feedback. Bij gebreke aan tijdige verstrekking van de correcte informatie of feedback heeft BYTEKLAAR het recht de uitvoering van de overeenkomt op te schorten en/of de uit de vertraging voortvloeiende additionele kosten in rekening te brengen conform artikel 7.2., of de overeenkomst te ontbinden ten laste van de klant wegens contractuele wanprestatie in hoofde van de klant. De klant vrijwaart BYTEKLAAR voor aanspraken van derden wegens schade voortvloeiend uit het onjuist of onvolledig karakter van de verstrekte informatie en gegevens.
               5.2.	    De klant erkent het belang van het aanleveren van de
               nodige informatie daar BYTEKLAAR diens dienstverlening hierop baseert. Onder door de klant aan te leveren informatie wordt onder meer verstaan: huisstijl, eventueel merkstijlgids, logo, visitekaartjes, flyers, afbeeldingen die vrij zijn van auteursrechten, logingegevens, het aantal webpagina’s, een overzicht van het aanbod in producten en diensten,  alle andere informatie die relevant is voor het invullen van de vragenlijst tijdens het intakegesprek, alsmede de benodigde feedback na elke vergadering. De klant dient deze informatie aan te leveren in het bestandstype en de kwaliteit of resolutie die BYTEKLAAR aan de klant gecommuniceerd heeft in de offerte.
               ARTIKEL 6 – TERMIJNEN
               6.1. 	De uitvoeringstermijn wordt steeds in onderling overleg bepaald, rekening houdende met de omvang en de complexiteit van de opdracht. Wanneer er geen uitvoeringstermijn werd overeengekomen, zal de opdracht uitgevoerd worden binnen een redelijke termijn, dan wel van zodra het verschuldigde voorschot van minstens 35% van de totale offerteprijs werd betaald door de klant.
               6.2. 	De opgegeven en overeengekomen termijn is steeds als indicatief te beschouwen. Bij overschrijding kan zij geen aanleiding vormen tot ontbinding van de overeenkomst of enige vorm van schadevergoeding, noch vormt dit een geldige reden tot weigering van betaling door de klant, behoudens in geval van aanzienlijke overschrijding van meer dan 4 maanden met een maximum 5% op de afgesproken prijs niet overschrijdt en enkel wanneer de aanzienlijke overschrijding niet te wijten is aan overmacht of gebeurtenissen in hoofde van de klant.
               6.3. 	Indien de opdracht door de klant wordt gewijzigd of de klant bijkomende opdrachten geeft, dewelke door BYTEKLAAR uitdrukkelijk worden aanvaard, zal de uitvoeringstermijn verlengd worden met de tijd die redelijkerwijze nodig is om deze wijzigingen of bijkomende opdrachten uit te voeren.
               ARTIKEL 7 – PRIJZEN EN BETALINGEN
               7.1.	    De vermelde prijzen worden weergegeven in euro (€),
               en zijn steeds exclusief btw voor klant-ondernemingen en inclusief btw voor klant-consumenten. In deze prijs is steeds 1 uur telefonische opvolging evenals 1 correctieronde inbegrepen. BYTEKLAAR draagt verder geen verantwoordelijkheid voor wat de bepaling van het juiste btw-tarief betreft. Indien op basis van de aan BYTEKLAAR meegedeelde informatie een foutief btw-tarief wordt toegepast en BYTEKLAAR hierdoor schade lijdt, zal BYTEKLAAR de klant voor deze schade kunnen aanspreken. Behoudens afwijkende schriftelijke afspraken zijn de kosten voor de benodigde materialen en hulpmiddelen voor het uitvoeren van de opdracht en manuren in de prijs inbegrepen.
               7.2.	    In onder meer volgende gevallen is BYTEKLAAR
               gerechtigd tot het aanrekenen van een meerprijs ten opzichte van de offerte:
               -	Tekstcorrecties;
               -	Extra correctieronde;
               -	Extra webpagina’s;
               -	Wijzigingen aan het formaat;
               -	Wijzigingen aan het tekstvolume;
               -	Werken bij hoogdringendheid;
               -	Integratie van nieuwe functies of plug-ins;
               -	Telefonische opvolging na het eerste inbegrepen uur;
               -	Implementeren van aanvullende beveiligingsvereisten
               -	Extra integratie met systemen of platforms, zoals
               bijvoorbeeld CRM-systemen;
               -	Het maken van foto’s door een fotograaf,
               gefactureerd via BYTEKLAAR;
               -	Alle werkzaamheden en prestaties op vraag van de
               klant uitgevoerd buiten de normale werktijd (zoals op   zaterdag, zondag of feestdagen);
               -	Overige diensten of opdrachten die niet in de initiële
               offerte werden opgenomen.
               De meerprijs wordt in onderling overleg met de klant bepaald. Indien er geen expliciete afspraken worden gemaakt, geldt het uurtarief van € 60,00/u (excl. btw) of € 72,60/u (incl. btw).
               Bovendien worden er verplaatsingskosten aangerekend aan een tarief van € 0,75/km (excl. btw) of € 0,91/km (incl. btw).
               7.3.	Partijen komen overeen dat een prijsherziening kan worden doorgevoerd door BYTEKLAAR als volgt. BYTEKLAAR behoudt zich het recht voor om rekening houdende met objectief meetbare schommelingen in grondstofprijzen, (materiaal)prijzen, lonen en sociale lasten, de overeengekomen prijs aan te passen volgens volgende formule: P1 = P0 x (0,2 + (L1/L0) x 0,4 + (M1/M0) x 0,4), waarbij P1 = prijsniveau in een gegeven jaar, P0 = prijsniveau in jaar 1 (basisniveau), L1 = loonkost in een gegeven jaar, L0 = loonkost in jaar 1 (basisjaar – lonen van kracht 10 kalenderdagen voor offerte), M1 = materieelkost in een gegeven jaar, M0 = materieelkost in jaar 1 (basisjaar – prijzen van kracht 10 kalenderdagen voor offerte). Hierbij is onderhavig beding slechts toepasselijk tot een bedrag van maximum 80% van de eindprijs, het beding verwijst naar parameters die reële kosten vertegenwoordigen en iedere parameter is alleen toepasselijk op dat gedeelte van de prijs dat beantwoordt aan de kosten die het vertegenwoordigt. In geval van een prijsstijging van meer dan 15% ten opzichte van de overeenkomst, verbindt BYTEKLAAR zich er evenwel toe de overeenkomst in onderling overleg met de klant te herzien en vooraleer de nieuwe prijs van kracht wordt, heeft de klant in dat geval het recht om de overeenkomst te beëindigen. BYTEKLAAR vermeldt op haar facturen of zij toepassing maakt van de formule en vermeldt hierop de gedetailleerde berekening.
               7.4.	De kostprijs voor goederen of diensten aangeleverd door derden in uitvoering van de overeenkomst wordt vervat in de offerte en facturatie van BYTEKLAAR en wordt door BYTEKLAAR in rekening gebracht bij de klant.
               7.5.	Zodra de bestelbon, offerte of orderbevestiging wordt aanvaard door BYTEKLAAR, bestaat er een betalingsverplichting in hoofde van de klant (aangezien de overeenkomst tussen partijen tot stand is gekomen). Deze betalingsverplichting mag enkel opgeschort worden indien er sprake is van opzettelijke tekortkomingen in hoofde van BYTEKLAAR, en dit beperkt tot het gedeelte van de opdracht waarop de vermeende tekortkoming betrekking heeft. De klant dient in dergelijk geval per schriftelijke kennisgeving (aangetekende brief of e-mail) het bewijs van de betreffende tekortkoming te leveren vóór het verstrijken van de betalingstermijn conform artikel 7.9.
               7.6.	De leveringen en diensten zijn contant betaalbaar, per overschrijving, elektronische betaling of bankcheque afhankelijk van de opdracht of dienstverlening. Alle betalingen dienen te gebeuren op het adres van de zetel van BYTEKLAAR.
               7.7.	BYTEKLAAR  behoudt zich het recht voor tot het vragen van een voorschot van minstens 35% van de totale offerteprijs. Afhankelijk van de omvang van de betrokken opdracht, behoudt BYTEKLAAR zich daarnaast het recht voor tot het werken met tussentijdse facturatie.
               7.8.	Opmerkingen met betrekking tot de factuur dienen uiterlijk binnen de 5 kalenderdagen na de factuurdatum schriftelijk (per aangetekende zending of per e-mail) kenbaar gemaakt te worden aan BYTEKLAAR.
               7.9.	Facturen dienen betaald te worden binnen de 15 kalenderdagen na factuurdatum (B2B en B2C), en dit zonder enige korting of inhouding van welke aard ook.
               Voor de klant-onderneming
               7.10.	Bij gebreke aan tijdige betaling door de klant-onderneming heeft BYTEKLAAR vanaf de vervaldag van rechtswege en zonder voorafgaande ingebrekestelling recht op moratoire interesten, waarbij de interestvoet gelijk is aan de wettelijke interestvoet overeenkomstig de Wet Betalingsachterstand van 2 augustus 2002. Bij niet-betaling op de vervaldag zal het factuurbedrag verhoogd worden met 10% ten titel van forfaitaire schadeloosstelling met een minimum van € 150,00, en een bedrag van € 75,00 euro ter dekking van de gemaakte buitengerechtelijke invorderingskosten, verschuldigd zijn. Dit geldt als forfaitaire schadevergoeding voor de andere kosten dan het renteverlies en de eigenlijke gerechtskosten en dit onverminderd het recht van BYTEKLAAR voor het vorderen van meerschade. Bovendien zal bij laattijdige betaling het resterende saldo en/of de nog niet vervallen facturen integraal en onmiddellijk opeisbaar worden.
               Voor de klant-consument
               7.11.	Bij gebreke aan tijdige betaling door de klant-consument houdt BYTEKLAAR zich eraan eerst een kosteloze herinnering te versturen aan de betrokken klant-consument. BYTEKLAAR erkent dat deze eerste herinnering de vorm dient aan te nemen van een ingebrekestelling, die minimaal de gegevens bevat zoals bepaald in artikel XIX.2, § 3 WER. BYTEKLAAR zal hierna een wettelijke wachttermijn respecteren van ten minste veertien kalenderdagen, dewelke ingaat vanaf de derde werkdag na verzending van de herinnering aan de klant-consument per post, of in geval van elektronische verzending vanaf de kalenderdag die volgt op de dag waarop de herinnering elektronisch werd overgemaakt aan de klant-consument. BYTEKLAAR behoudt zich het recht om na het verstrijken van deze termijn moratoire interesten te kunnen vorderen overeenkomstig artikel XIX.4, eerste lid, 1° WER. Bovendien zal voor de klant-consument pas na het volbrengen van bovenstaande formaliteiten het factuurbedrag verhoogd kunnen worden ten titel van forfaitaire schadeloosstelling, en dit rekening houdend met de begrenzingen zoals bepaald in artikel XIX. 4, eerste lid 2° WER. Dit geldt als forfaitaire schadevergoeding voor de andere kosten dan het renteverlies en de eigenlijke gerechtskosten en dit onverminderd het recht van BYTEKLAAR voor het vorderen van meerschade.
               7.12.	BYTEKLAAR behoudt zich het recht voor om bij gebreke aan tijdige betaling van de factuur de overeenkomst zonder ingebrekestelling of gerechtelijke tussenkomst op te schorten, dan wel met onmiddellijke ingang te beëindigen op kennisgeving per aangetekende post, zonder enig recht op schadevergoeding in hoofde van de klant.
               7.13.	BYTEKLAAR behoudt zich het recht voor om schuldvorderingen ten opzichte van de klant te compenseren met eventuele financiële vorderingen van de klant opzichtens BYTEKLAAR, ook indien er geen samenhang voorhanden is.
               ARTIKEL 8 – DOMEINNAMEN, WEBHOSTING EN ONDERHOUDSCONTRACTEN
               8.1.	    Diensten met betrekking tot domeinnamen, webhost-
               ing, mailboxen, support, onderhoud en/of andere periodieke dienstverleningen
               zoals bijvoorbeeld SEO-diensten, worden standaard aangeboden voor een periode van minstens twaalf maanden. Opzegging van dergelijke periodieke dienstverleningen kan door beide partijen worden gedaan, mits dit uiterlijk twee maanden vóór de vervaldatum van de contracttermijn geschiedt door middel van een met reden omkleed schrijven (per e-mail of aangetekende brief). Vroegtijdige beëindiging van een periodieke dienstverlening door de klant, geeft de klant geen aanspraak op restitutie voor de nog resterende contractduur.
               8.2.	     BYTEKLAAR kan niet aansprakelijk worden
               gehouden voor enige schade die voortvloeit uit gebreken in de dienstverlening met betrekking tot webhosting, ongeacht de oorzaak van dergelijke gebreken.
               8.3.	De registratie van een domeinnaam geschiedt standaard op naam van de klant, behoudens andersluidend schriftelijke overeenkomst tussen partijen. Daar het registreren van een domeinnaam mede bepaald wordt door nationale en internationale regelgeving, kan BYTEKLAAR geen enkele garantie bieden met betrekking tot de registratie van de door de klant gewenste domeinnaam, zelfs indien blijkt dat deze nog beschikbaar is op het moment van de aanvraag. De verbintenis van BYTEKLAAR betreft hier dan ook een inspanningsverbintenis. Voor wat betreft de .be-domeinnamen verklaart de klant zich akkoord met de algemene voorwaarden voor eindgebruikers zoals vastgesteld door DNS vzw, dewelke consulteerbaar zijn op www.dnsbelgium.be
               ARTIKEL 9 – BEWARING
               9.1.	Behoudens uitdrukkelijk overeengekomen in een voorafgaandelijke overeenkomst tussen partijen, is BYTEKLAAR niet gehouden tot de bewaring of archivering van bestanden na oplevering aan de klant.
               9.2.	Ingeval de klant toch om bewaring verzoekt, gebeurt dit steeds op risico van de klant. BYTEKLAAR is bijgevolg niet aansprakelijk voor beschadigingen of verlies aan de te bewaren bestanden, behalve in geval van opzet of zware fout conform artikel 13.6.
               9.3.	BYTEKLAAR is niet verantwoordelijk voor data opgeslagen op harde schijven van de klant, noch voor back-ups of back-upsystemen.
               ARTIKEL 10 - CORRECTIES
               10.1.	Wijzigingen in het oorspronkelijk order van welke aard ook (in de tekst, in de bewerking of plaatsing van illustraties, in de formaten etc.), schriftelijk of op een andere wijze, door of namens de klant aangebracht, worden aan de klant doorgerekend aan een meerprijs conform artikel 7.2., en verlengen vanzelfsprekend de uitvoeringstermijn.
               10.2.	Mondelinge, telefonische of per sociale media meegedeelde correcties door de klant zijn op risico van de klant en worden in geval van betwisting slechts erkend wanneer deze schriftelijk bevestigd werden door BYTEKLAAR.
               ARTIKEL 11 – GEBRUIK VAN DRONES
               11.1.	BYTEKLAAR is houder van een geldig UAS-operatornummer. Dit nummer is steeds duidelijk zichtbaar op alle door haar gebruikte drones, in overeenstemming met de vereisten voor traceerbaarheid en verantwoordelijkheid.
               11.2.	BYTEKLAAR erkent het belang van privacy- en gegevensbescherming en verbindt zich ertoe de toepasselijke privacywetgeving na te leven bij het uitvoeren van drone-operaties.
               11.3.	BYTEKLAAR zal enkele drone-operaties uitvoeren binnen de toegestane categorieën en zones. Dit omvat, maar is niet beperkt tot, het opereren binnen de “open categorie”, met name in subcategorieën A1 en A3, waarbij:
               - In subcategorie A1 enkel kleine dronetypes C0 en C1 evenals sommige lichte ‘legacy drones’ worden gebruikt in de nabijheid van mensen en gebouwen;
               - In subcategorie A3 voldoende afstand zal bewaard worden van mensen en gebouwen met grotere en/of oudere drones, om veiligheid en naleving van de toepasselijke regelgeving te waarborgen.
               11.4.	BYTEKLAAR hanteert steeds de nodige veiligheidsprocedures bij het uitvoeren van drone-operaties. Dit omvat het implementeren van voorzorgmaatregelen voor bijvoorbeeld botsingen, het respecteren van no-fly zones en het handhaven van een veilige afstand van verboden of gevoelige gebieden.
               ARTIKEL 12 - EIGENDOMSVOORBEHOUD
               12.1.		BYTEKLAAR blijft eigenaar van alle in het kader van de dienstverlening aangewende of aangeleverde werken en bijhorende intellectuele rechten tot aan de integrale betaling door de klant. BYTEKLAAR behoudt zich het recht voor om zonder voorafgaandelijke verwittiging de geleverde werken (bv. website) terug te nemen indien de klant dienst betalingsverbintenis niet (tijdig) naleeft, zelfs indien er reeds incorporatie, vermenging of verwerking met andere werken heeft voorgedaan. Eventueel betaalde voorschotten blijven verworven bij wijze van compensatie van de mogelijke verliezen die BYTEKLAAR lijdt bij de reeds aangevatte dienstverlening.
               ARTIKEL 13 – GARANTIES, GEBREKEN EN BURGELIJKE AANSPRAKELIJKHEID
               13.1.	De klant heeft de verplichting om via een met reden omkleed schrijven (aangetekende brief of e-mail) tekortkomingen met betrekking tot de geleverde diensten te melden aan BYTEKLAAR en dit binnen de 10 kalenderdagen nadat de diensten zijn geleverd. Bij gebreken of tekortkomingen die tijdig werden gemeld en waarvan BYTEKLAAR meent dat deze gegrond zijn, beschikt zij over een termijn van 30 kalenderdagen om hieraan tegemoet te komen, alvorens de klant beroep kan doen op diens overige rechten (ontbinding, schadevergoeding, etc.). Bij gebreke aan (tijdige) reactie, wordt de klant geacht akkoord te gaan met de geleverde diensten, en kan de klant geen aanspraak maken op een schadevergoeding.
               13.2.	Gebreken in de uitvoering of niet-conformiteit van de dienstverlening, dewelke zichtbaar waren op het ogenblik van het uitvoeren van de toevertrouwde opdracht en waarvan de klant wordt geacht kennis genomen te hebben, worden gedekt door de aanvaarding van de dienstverlening en komen niet in aanmerking voor enige vorm van schadeloosstelling door BYTEKLAAR, onverminderd of deze voortvloeien uit handelingen of omissies in hoofde van BYTEKLAAR. Deze aanvaarding kan uitdrukkelijk, dan wel stilzwijgend plaatsvinden.
               13.3.	Voor gebreken in de uitvoering, dewelke onzichtbaar waren op het ogenblik van de beëindiging van de opdracht, zal BYTEKLAAR tot geen vrijwaring gehouden zijn, tenzij deze het gevolg zijn van een zware fout, opzettelijke fout, bedrog, dan wel fraude. De klant is verplicht BYTEKLAAR te verwittigen binnen de 10 kalenderdagen vanaf het ogenblik dat een tekortkoming of gebrek wordt vastgesteld of men zich hiervan bewust geweest moest zijn. Dit door middel van een met reden omkleed schrijven (per e-mail of aangetekende brief), inclusief foto’s. Bij gebreke aan (tijdige) reactie, wordt de klant geacht akkoord te gaan met de geleverde werkzaamheden, en kan de klant geen aanspraak maken op een schadevergoeding. Bij gebreken die tijdig worden gemeld en waarvan BYTEKLAAR meent dat deze gegrond zijn, beschikt zij over een termijn van 30 kalenderdagen om tegemoet te komen aan de vermeende tekortkoming, alvorens de klant beroep kan doen op diens overige rechten (ontbinding, schadevergoeding, etc.).
               13.4.	BYTEKLAAR is daarenboven nooit aansprakelijk voor:
               - Schade aan data;
               - Schade aan software;
               - Schade aan gegevensdragers;
               - Schade voortvloeiend uit spellings-, taalkundige
               of grammaticale fouten;
               - Schade voortvloeiend uit de achteruitgang van programma’s en apparatuur dewelke bij aanvang van de overeenkomst reeds    eigendom waren van de klant.
               13.5.	Het recht op garantie en/of waarborg komt te vervallen wanneer a) de klant zich voor de melding van een gebrek niet houdt aan hetgeen onder artikel 13.1. en 13.3. werd bepaald, b) de klant zich niet als een voorzichtig en redelijk persoon ontfermd heeft over de diensten conform het normale doel waarvoor deze bestemd zijn, met inbegrip van periodiek onderhoud of c) wanneer er manipulatie van de diensten door de klant of door een derde heeft plaatsgevonden.
               13.6.		BYTEKLAAR kan slechts aansprakelijk worden gesteld voor opzet, zware fout of voor die van aangestelden of lasthebbers, fraude of bedrog, alsook voor het niet uitvoeren van de essentiële verbintenissen die het voorwerp van de overeenkomst uitmaken. Gebreken dewelke intrinsiek aanwezig waren in het behandelde object, dan wel voortvloeien uit verkeerdelijk verschafte informatie of uitdrukkelijke instructies door de klant, kunnen geen aanleiding tot aansprakelijkheid geven in hoofde van BYTEKLAAR. Ook gebreken aan de hard-software en randapparatuur van de klant waarop de dienstverlening wordt uitgevoerd (bv. incompatibele software, verouderde besturingssystemen, eigenhandig ingrijpen van de klant op de digitale gebruikservaring, etc.) geven geen aanleiding tot aansprakelijkheid van BYTEKLAAR.
               13.7. 	De klant vrijwaart BYTEKLAAR in hoofdsom, kosten en interesten voor eventuele aanspraken van derden, die in verband met de uitvoering van de overeenkomst schade (beweren) geleden te hebben, in het bijzonder in toepassing van artikel 544 B.W./artikel 3.101 Nieuw B.W. inzake burenhinder.
               13.8. 	In geval van aansprakelijkheid in hoofde van BYTEKLAAR blijft de vergoedbare schade beperkt tot directe materiële schade en letselschade die het rechtstreekse gevolg zijn van een toerekenbare tekortkoming en is de maximale schadevergoeding beperkt tot het bedrag waarvoor de verzekering tussenkomst verleent, dan wel beperkt tot 10% van het factuurbedrag, met een maximum van € 500,00, voor de betrokken werkzaamheden indien de verzekering geen dekking verleent. BYTEKLAAR heeft een verzekering burgerlijke aansprakelijkheid afgesloten bij een in België gevestigde verzekeraar. Op eenvoudig verzoek kan aan de klant een verzekeringsattest worden bezorgd. Dit attest bevat algemene informatie met betrekking tot de door BYTEKLAAR afgesloten burgerlijke aansprakelijkheidspolis. Verder is BYTEKLAAR niet aansprakelijk voor vermogensschade, indirecte schade of gevolgschade.
               13.9. 	Iedere vordering van de klant tot schadevergoeding dient steeds te worden ingesteld binnen een termijn van 3 maanden nadat de feiten waarop deze vordering wordt gebaseerd gekend waren door de klant of redelijkerwijze gekend konden zijn. Indien de vordering niet binnen deze termijn wordt ingesteld, komt deze te vervallen wegens verjaring.
               ARTIKEL 14 – OVERMACHT EN BEËINDIGING OVEREENKOMST
               Overmacht en verandering van omstandigheden
               14.1.	In geval van tijdelijke overmacht worden de verplichtingen van BYTEKLAAR onder deze overeenkomst, geschorst of beperkt gedurende de periode van overmacht zonder enige aansprakelijkheid in hoofde van BYTEKLAAR.
               14.2.	Onder overmacht dient te worden verstaan: elke onvoorzienbare en onvermijdbare gebeurtenis onafhankelijk van de wil van BYTEKLAAR die een onoverkomelijk beletsel uitmaakt voor de nakoming van diens verbintenis, zoals, maar niet beperkt tot pandemie, langdurige ziekte, overlijden, wilde staking of lockdown, vertraging in aanlevering of uitputting van materialen, langdurige hacking van software, het niet tijdig opleveren van werken door andere aannemers waarvan BYTEKLAAR afhankelijk is, extreme weersomstandigheden, faillissement leverancier, het niet ter beschikking zijn van water of elektriciteit, technische storing, embargo’s, wettelijke verplichtingen, terrorisme of oorlog.
               14.3.	Indien door overmacht de overeenkomst gedurende zes maanden, niet kan uitgevoerd worden en aldus niet meer als tijdelijk aanzien kan worden, hebben zowel BYTEKLAAR als de klant het recht om de overeenkomst door middel van aangetekend schrijven te herzien of te beëindigen, zonder dat schadevergoeding verschuldigd is aan de andere partij. De klant is gehouden tot het vergoeden van alle door BYTEKLAAR tot op dat ogenblik geleverde prestaties en gemaakte kosten. In het geval de overmacht te wijten is aan de uitputting van materialen of het faillissement van leveranciers is BYTEKLAAR in afwijking van hetgeen in deze bepaling werd opgenomen, gerechtigd om in een vervanging door gelijkwaardige materialen te voorzien. BYTEKLAAR zal de klant hiervan in kennis stellen, dewelke op zijn beurt het recht heeft om bezwaar te uiten, waarna er in onderling overleg naar een oplossing toe gewerkt zal worden.
               Annulering/vroegtijdige opzegging
               14.4.	Indien de overeenkomst door de klant eenzijdig, geheel of deels, uitdrukkelijk of impliciet, voortijdig opgezegd wordt, heeft BYTEKLAAR van rechtswege en zonder voorafgaande ingebrekestelling recht op 1) betaling door de klant van de reeds uitgevoerde werkzaamheden, de reeds door BYTEKLAAR gemaakte kosten en de reeds geleverde materialen, en 2) bijkomend een door de klant te betalen beëindigingsvergoeding voor de gederfde winst forfaitair begroot op 30% van de offerteprijs van de opdracht met een minimum van € 250,00. Deze forfaitaire vergoeding laat het recht van BYTEKLAAR om betaling te vorderen van een aantoonbare hoger werkelijk geleden schade onverlet.
               14.5.	De klant kan de overeenkomst met BYTEKLAAR na het versturen van een aangetekende ingebrekestelling waarin een ultieme respijttermijn wordt gegund aan BYTEKLAAR, zonder voorafgaande rechterlijke tussenkomst en zonder vergoeding noch inachtneming van een opzeggingstermijn ontbinden, in geval van een ernstige contractuele wanprestatie door BYTEKLAAR.
               Ontbinding wegens ernstige contractuele wanprestatie
               14.6.	BYTEKLAAR kan de overeenkomst met de klant met onmiddellijke ingang, zonder voorafgaande ingebrekestelling en zonder rechterlijke tussenkomst, zonder vergoeding, schadeloosstelling of inachtneming van een opzeggingstermijn ontbinden, in geval van een ernstige contractuele wanprestatie door de klant. Partijen komen uitdrukkelijk overeen dat de volgende punten niet-limitatief zullen worden beschouwd als ernstige contractuele wanprestatie: de niet-betaling van het voorschot en/of de facturen van BYTEKLAAR, het niet tijdig verschaffen van de noodzakelijke informatie voor de uitvoering van de opdracht, fraude, verduistering, slechtmaking van BYTEKLAAR door de klant, faillissement, liquidatie, kennelijk onvermogen of vermoeden van insolvabiliteit van de klant. Het recht van BYTEKLAAR om de overeenkomst in dit geval te ontbinden, laat diens recht op vergoeding van de reeds uitgevoerde werkzaamheden en aangeleverde materialen onverlet.
               ARTIKEL 15 – ZEKERHEDEN EN PAND
               15.1.		Tot waarborg van de betaling van de door de klant aan BYTEKLAAR verschuldigde sommen in hoofdsom, rente en kosten, geeft de klant ten voordele van BYTEKLAAR in pand:
               15.2.		Al zijn huidige en toekomstige schuldvorderingen opzichtens BYTEKLAAR (als schuldenaar van de schuldvordering(en), erkent BYTEKLAAR uitdrukkelijk kennis te nemen van het pand.
               15.3.		Al zijn huidige en toekomstige schuldvorderingen op derden, uit welke hoofde ook. Bedoelt worden onder meer vorderingen van de klant uit handelscontracten, vorderingen van de klant uit hoofde van prestaties en diensten, vorderingen van de klant uit opbrengsten van roerende of onroerende goederen, vorderingen van de klant uit hoofde van pensioenen, vorderingen voortvloeiend uit de beroeps- en handelsactiviteit van de klant, vorderingen van de klant op bank- of andere financiële instellingen, vorderingen van de klant in contractuele en buitencontractuele aansprakelijkheid, vorderingen van de klant uit hoofde van verzekeringen, vorderingen van de klant op de overheid en andere publiekrechtelijke rechtspersonen, vorderingen van de klant met betrekking tot de sociale zekerheid. Voormelde opsomming is exemplatief.
               15.4.		Het pand op schuldvorderingen maakt de klant inningsonbevoegd.
               15.5.		BYTEKLAAR is ertoe gerechtigd om de debiteur van de verpande schuldvordering(en) van zijn klant in kennis te stellen van de verpanding, en alles te doen om dit pand tegenwerpelijk te maken aan derden, dit op kosten van de klant die de schuldvordering(en) in pand gaf.
               15.6.		Op eerste verzoek van BYTEKLAAR deelt de klant alle nuttige informatie mee die BYTEKLAAR in staat stelt om tot inning van de verpande schuldvordering(en) over te gaan.
               15.7.		BYTEKLAAR zal de uit hoofde van de verpande schuldvordering(en) verschuldigde sommen rechtstreeks kunnen innen opzichtens de debiteur van de verpande schuldvordering(en), zonder voorafgaande ingebrekestelling van deze laatste.
               15.8.		Indien de klant nalaat om binnen de 14 kalenderdagen vanaf het eerste verzoek van BYTEKLAAR alle nuttige informatie m.b.t. de identiteit van de debiteur van de verpande schuldvordering(en) te verschaffen, houdt dit een toerekenbare niet-nakoming door de klant uit, dewelke zonder voorafgaande ingebrekestelling aanleiding kan geven tot een ontbinding van rechtswege van de overeenkomst lastens de klant, onverminderd het recht van BYTEKLAAR op een forfaitaire schadevergoeding van tweehonderdvijftig (€ 250,00).
               15.9.		Het akkoord met onderhavige algemene voorwaarden veronderstelt de toelating en het mandaat aan BYTEKLAAR om, bij gebreke aan kennisgeving binnen de 14 kalenderdagen vanaf het eerste verzoek door BYTEKLAAR de relevante informatie omtrent de schuldvorderingen van de klant op te vragen bij de Ontvanger van de btw.
               ARTIKEL 16 – INTELLECTUELE EIGENDOMS- RECHTEN
               16.1.	De (bron)codes, scripts, ontwerpen, documenten, ideeën, procestechnieken en andere creaties die in het kader van de dienstverlening worden aangewend of gecreëerd blijven de uitsluitende intellectuele eigendom van BYTEKLAAR, met een louter gebruiksrecht voor de klant. Ook merken, octrooien, handelsnamen, auteursrechten, sui generis beschermingsregimes en knowhow met betrekking tot de producten en diensten zullen steeds en onherroepelijk intellectuele en industriële eigendom zijn en blijven van BYTEKLAAR. Alle door de klant aangeleverde informatie, bestaande uit o.m. bedrijfsstrategieën, foto’s en bestanden, blijven evenwel eigendom van de klant of de rechthebbende derde.
               16.2.	Het is de klant verder niet toegestaan de informatie, knowhow, documenten, ideeën of procestechnieken, dewelke tot de uitsluitende intellectuele eigendom van BYTEKLAAR behoren, te imiteren, te wijzigen of te modificeren zonder voorafgaandelijke schriftelijke toestemming van BYTEKLAAR.
               16.3.	Tenzij uitdrukkelijk anders is overeengekomen in een schriftelijke overeenkomst tussen partijen, is het de klant niet toegestaan om
               vertrouwelijke informatie, die expliciet als zodanig is aangeduid of die redelijkerwijze als vertrouwelijk beschouwd dient te worden, of enige informatie die eigendom is van of onder controle van BYTEKLAAR valt, inclusief maar niet beperkt tot de creaties beschermd onder intellectuele eigendomsrechten van BYTEKLAAR, te reproduceren, openbaar te maken of aan derden kenbaar te maken zonder voorafgaande schriftelijke toestemming van BYTEKLAAR op straffe van een schadevergoeding die forfaitair wordt vastgesteld op minstens 20% van de totale offerteprijs van de uitgevoerde opdracht, onverminderd het recht op een eventueel hogere vergoeding voor bewezen meerschade.
               16.4.	De URL’s van de webportalen die privé toegang bieden, alsook eventuele privé inlogcodes mogen onder geen beding worden doorgegeven aan derden.
               ARTIKEL 17 – GEBRUIK NAAM
               17.1.	BYTEKLAAR heeft het recht om de naam, het logo, desgevallend brochures of andere realisaties van de klant te gebruiken voor promotionele doeleinden, waaronder publicatie van haar naam en logo op de website of sociale media van BYTEKLAAR, alsook voor het gebruik van interne doeleinden.
               17.2.	BYTEKLAAR heeft het recht om haar eigen naam en logo zichtbaar te maken op de geleverde werken of geleverde websites en webshops. Indien de klant niet wenst dat BYTEKLAAR haar naam en logo zichtbaar maakt op de geleverde werken, waaronder websites en webshops, kan hierover in onderling overleg een overeenkomst worden bereikt. Er zal dan een prijs worden bepaald die de klant verschuldigd is aan BYTEKLAAR voor het afzien van dit recht.
               17.3.	De klant mag de naam van BYTEKLAAR niet gebruiken zonder de voorafgaande, uitdrukkelijke schriftelijke toestemming van BYTEKLAAR.
               ARTIKEL 18 – PRIVACY- EN GEGEVENS- BESCHERMING
               18.1.	      BYTEKLAAR erkent het belang van een veilige
               verwerking van persoonsgegevens (waaronder naam, adres, e-mailadres, locatiegegevens en overige persoonlijke data van natuurlijke personen) conform de heersende nationale regelgeving, waaronder de wet van 30 juli 2018, alsmede Verordening (EU) 2016/679 en tracht deze na te leven.
               18.2.       De door BYTEKLAAR verzamelde persoonsgegevens zullen uitsluitend aangewend worden ter uitvoering van de opdracht op basis
               van de contractuele relatie tussen partijen, het gerechtvaardigd belang of op basis van een andere rechtvaardigingsgrond. BYTEKLAAR erkent de persoonsgegevens steeds vertrouwelijk te zullen verwerken ten behoeve van of in opdracht van de klant.
               18.3.	       BYTEKLAAR garandeert dat persoonsgegevens
               verzameld en verwerkt worden op een transparante wijze en dit enkel voor welbepaalde, uitdrukkelijk omschreven en gerechtvaardigde doeleinden. Iedere verwerking wordt beperkt tot hetgeen noodzakelijk is voor de doeleinden waarvoor de verwerking plaatsvindt. BYTEKLAAR verwerkt persoonsgegevens voor de volgende doeleinden: uitvoering van de overeenkomst, boekhoudkundige doeleinden en wettelijke verplichtingen. BYTEKLAAR ziet er op toe dat de persoonsgegevens correct worden geregistreerd en geactualiseerd indien nodig.
               18.4.	Door beroep te doen op de dienstverlening van BYTEKLAAR aanvaardt de klant dat deze gegevens verwerkt kunnen worden. BYTEKLAAR maakt gebruik van subverwerkers die in opdracht en onder toezicht van BYTEKLAAR persoonsgegevens verwerken. Deze verwerkingen zullen ten allen tijden beperkt worden tot het strikt noodzakelijke voor het uitvoeren van de respectievelijke opdracht. Behoudens in relatie tot de medewerkers en subverwerkers die in het kader van de dienstverlening betrokken worden, zal BYTEKLAAR geen persoonsgegevens uitwisselen met derden, tenzij dit a) noodzakelijk is voor de uitvoering van de overeenkomst, b) voortvloeit uit wettelijke bepalingen, gerechtelijke- of overheidsbevelen of c) in geval van uiterste noodzaak.
               18.5.	BYTEKLAAR verbindt zich er toe de nodige technische en organisatorische maatregelen te zullen treffen om verlies of enige andere vorm van onrechtmatige verwerking van persoonsgegevens tegen te gaan, rekening houdende met de stand van de techniek, de gebruiken in de betrokken sector, en de aard van de verwerking.
               18.6.	De klant heeft het recht op inzage, kosteloze verbetering en/of weglating van diens verzamelde persoonsgegevens te verzoeken, alsmede het recht om diens toestemming in te trekken of om de overdraagbaarheid van diens gegevens te verzoeken. De door BYTEKLAAR verzamelde gegevens kunnen geraadpleegd worden na schriftelijk verzoek aan BYTEKLAAR (3665 As, Lanklaarsesteenweg 31, of info@byteklaar.be).
               18.7.	De persoonsgegevens die voor het opmaken van de offerte of het uitvoeren van de opdracht worden opgevraagd, worden niet langer bewaard dan noodzakelijk voor de uitvoering van de desbetreffende dienstverlening. Indien BYTEKLAAR de gegevens voor een langere periode bewaart, baseert zij zich hier ten alle tijden voor op de nodige rechtvaardigingsgronden, waaronder de wettelijke verplichtingen inzake boekhouding, aansprakelijkheid en garantie.
               18.8.	Vragen en/of klachten met betrekking tot de verwerking van uw persoonsgegevens kunnen gericht worden aan het centrale contactpunt bij BYTEKLAAR (info@byteklaar.be of 0477 20 99 33). Voor meer informatie kan u steeds de website van de Gegevensbeschermingsautoriteit (www.gegevensbeschermingsautoriteit.be).
               ARTIKEL 19 – GEEN ONEVENWICHTIGHEID TUSSEN RECHTEN EN PLICHTEN VAN PARTIJEN – RISICOVERDELING – VERDISCON- TEERD IN DE VERGOEDING
               19.1.       Partijen bevestigen uitdrukkelijk dat de rechten en plichten zoals opgenomen in onderhavige algemene voorwaarden de consensus
               tussen partijen en derhalve de werkelijke wil van partijen inhouden. Deze algemene voorwaarden brengen hierin dan ook geen onevenwichtigheid teweeg. De in onderhavige algemene voorwaarden bedongen risicoverdeling werd verdisconteerd in de overeengekomen prijs.
               ARTIKEL 20 – NIETIGHEID
               20.1.      Elk artikel van onderhavige algemene voorwaarden dient te worden geïnterpreteerd op een wijze die verenigbaar is met de toepasselijke
               wetgeving. Eventuele nietigheid van een clausule zal niet de nietigheid van de volledige overeenkomst met zich meebrengen. De overeenkomst zal in dit geval worden hervormd en afgedwongen alsof de nietige clausule nooit opgenomen is geweest. Partijen zullen in dat geval tot een nieuwe overeenkomst trachten te komen waardoor zoveel mogelijk eenzelfde doelstelling of economisch evenwicht tussen partijen wordt bereikt als de niet afdwingbare bepaling bewerkstelligde.
               ARTIKEL 21 –TOEPASSELIJK RECHT EN BEVOEGDHEID
               21.1.	     De overeenkomst en alle daaruit voortvloeiende
               handelingen worden exclusief beheerst door het Belgische Recht en dienen overeenkomstig de Belgische wetgeving te worden geïnterpreteerd.
               21.2.      Uitsluitend de rechtbanken behorende tot het gerechtelijk arrondissement waar de zetel van BYTEKLAAR is gevestigd, zijn bevoegd om kennis te nemen van geschillen tussen de klant en BYTEKLAAR die uit de overeenkomst of de toepassing van de algemene voorwaarden voortvloeien of hiermee enig verband houden.

           </p>
       </div>
    )
}